### ISSUE TITLE
import $url

### ISSUE THREAD

**Issue by bblfish** [ThoughtWorksInc/import.scala#1]
Hi, I discussed this issue on the ammonite github repository [import URLs issue 655](https://github.com/lihaoyi/Ammonite/issues/655).

So clearly support http, https urls would allow one to point to a script on the web (or ftp, ...) and
be able to execute it locally.

But even more intersting is support for relative URLs  as that would allow scripts to be written that could work locally when the local file is retrieved via a file operation, sine then relative URLs turn into `file://` urls, or to `https://` urls when the exact same script is published on the web (or ftp urls if they get publised on `ftp`, ...) . Actually once this is noticed it becomes clear that `import $file` is no longer needed since `import $url` covers that space)

Since  dotty will I am told by @nafg support VS Code compiler, giving a number of editors immediate support for a number of features such as code highlighting, code completion, etc... [see the list](http://langserver.org/#implementations-client), having the compiler understand the ammonite convention would be really nice, as it would immediately give us a number of editors to work with Ammonite scripts.

**Comment by Atry** [comment]
This `Import.scala` plugin has supported importing URLs.

In fact `import $url` is an alias of `import $file` in `Import.scala` plugin. https://github.com/ThoughtWorksInc/Import.scala/blob/master/src/main/scala/com/thoughtworks/Import.scala#L83

**Comment by Atry** [comment]
Also this `Import.scala` plugin has supported relative URLs.

**Comment by Atry** [comment]
Close this issue because the requested feature had been there already.

**Comment by bblfish** [comment]
great! sorry I did not check... (I don't know less than a little about compiler plugins...)
